name: 'KiCAD schematic PDF'
inputs:
  schematic:
    description: 'Top-level schematic to render'
    required: true
  output_directory:
    description: 'Output Directory'
    required: false
    default: 'tmp/rendered'
runs:
  using: 'docker'
  image: 'setsoft/kicad_auto:10.4-5.1.6'
  args: [ 'eeschema_do', 'export', '-f', 'pdf', '-a', '${{ inputs.schematic }}', '${{ inputs.output_directory }}' ]
